### PR TITLE
Revert Thermal recipes to JSON

### LINKED ISSUE #451: Cannot connect to server on version 1.8.0
### Modpack Version

1.8.0

### Describe your issue.

We've just attempted to upgrade from 1.3.0 to 1.8.0, and we cannot log into the server. The issue is exactly the same as the one seen in #229 but the workaround posted there hasn't worked.

With the `refinery.js` and `smelter.js` files removed, we now get the following error (server-side) upon joining:
`Lorcogoth lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.ClassCastException: class cofh.lib.util.crafting.IngredientWithCount cannot be cast to class dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient (cofh.lib.util.crafting.IngredientWithCount is in module cofh_core@10.2.1 of loader 'TRANSFORMER' @3e0a9b1d; dev.latvian.mods.kubejs.platform.forge.ingredient.KubeJSIngredient is in module kubejs@1902.6.0-build.142 of loader 'TRANSFORMER' @3e0a9b1d)`

### Crash Report

_No response_

### Latest Log

https://gist.github.com/sniggyfigbat/990d5a617f5e3c8380bde82beadf7567

### Have you modified the modpack?

No

### User Modifications

_No response_

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

_No response_

### PR DESCRIPTION
**Pull request by MuteTiefling**
Should resolve #451

### CODE REVIEW

File: kubejs/server_scripts/normal/recipes/thermal/centrifuge.js [hunk 1]
```diff
@@ -1,30 +1 @@
-ServerEvents.recipes((event) => {
```
Comment (NielsPilgaard) [inline kubejs/server_scripts/normal/recipes/thermal/centrifuge.js:1]: Why remove these entirely?

Comment (MuteTiefling) [reply kubejs/server_scripts/normal/recipes/thermal/centrifuge.js:1]: The material doesn't exist anymore

Comment (NielsPilgaard) [reply kubejs/server_scripts/normal/recipes/thermal/centrifuge.js:1]: Ah okay 😅
